[env:esp32dev]
platform = espressif32
board = esp32dev            ; change to your exact board (e.g. esp32doit-devkit-v1, nodemcu-32s)
framework = arduino
monitor_speed = 115200
lib_deps =
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
build_flags =
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=0
    -D CONFIG_ASYNC_TCP_STACK_SIZE=16384